# Training settings
training:
  epochs: 50
  batch_size: 16
  warmup_epochs: 5
  lr: 0.005
  min_lr: 1.0e-6
  weight_decay: 0.0001
  num_cores: 6
  text_image: True
  clip_pretrained_model_name: "openai/clip-vit-base-patch32" # Choose when text_image is True

# Model settings
model:
  d_model: 1024
  in_channels: 3
  image_size: 256
  patch_size: 16
  num_heads: 8
  num_layers: 6
  num_timesteps: 1000
  specific_timesteps: 256
  final_embedding_dim: 768
  saved_all_data_first: false # Recommended to be false cause it needs a lot of memory

# Data settings
data:
  image_dir: '/content/drive/MyDrive/Dataset/DIV2K/3patches'  # Path to training directory
  valid_dir: '/content/drive/MyDrive/Dataset/validation_patches'  # Path to validation directory
  clean_image: '/content/drive/MyDrive/cleanImage.pt' # Path to clean image directory
  valid_image: '/content/drive/MyDrive/validImage.pt' # Path to valid image directory
  num_workers: 0

# Logging settings
logging:
  log_dir: '/content/drive/MyDrive/D4D/logs'
  use_wandb: false
  project_name: 'noise-estimation-clip'

# Checkpoint settings
checkpoint:
  resume_from: null  # Path to checkpoint if resuming
  resetLR: false